// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVo_SIDEHXbhtKPpnHF9i3DZKMQixvKxU',
    appId: '1:601778585822:web:e49547d207f40eab8dc24f',
    messagingSenderId: '601778585822',
    projectId: 'walletar-app',
    authDomain: 'walletar-app.firebaseapp.com',
    databaseURL: 'https://walletar-app-default-rtdb.firebaseio.com',
    storageBucket: 'walletar-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKDaBCsBbJTVX-8l4X6Tt1rEDrDw-7wrk',
    appId: '1:601778585822:android:8e5cfe94b613f79d8dc24f',
    messagingSenderId: '601778585822',
    projectId: 'walletar-app',
    databaseURL: 'https://walletar-app-default-rtdb.firebaseio.com',
    storageBucket: 'walletar-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-swf2eIV9eBjkKiYRA8lnILEnOT48jqk',
    appId: '1:601778585822:ios:104f0187591b03cb8dc24f',
    messagingSenderId: '601778585822',
    projectId: 'walletar-app',
    databaseURL: 'https://walletar-app-default-rtdb.firebaseio.com',
    storageBucket: 'walletar-app.firebasestorage.app',
    iosBundleId: 'com.example.walletar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-swf2eIV9eBjkKiYRA8lnILEnOT48jqk',
    appId: '1:601778585822:ios:104f0187591b03cb8dc24f',
    messagingSenderId: '601778585822',
    projectId: 'walletar-app',
    databaseURL: 'https://walletar-app-default-rtdb.firebaseio.com',
    storageBucket: 'walletar-app.firebasestorage.app',
    iosBundleId: 'com.example.walletar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVo_SIDEHXbhtKPpnHF9i3DZKMQixvKxU',
    appId: '1:601778585822:web:724abe8d9c814f3b8dc24f',
    messagingSenderId: '601778585822',
    projectId: 'walletar-app',
    authDomain: 'walletar-app.firebaseapp.com',
    databaseURL: 'https://walletar-app-default-rtdb.firebaseio.com',
    storageBucket: 'walletar-app.firebasestorage.app',
  );
}
